export const SELECT_NAV = "SELECT_NAV";
export const SELECT_DESTINATION = "SELECT_DESTINATION";
export const TOGGLE_SHOW_CONTENT = "TOGGLE_SHOW_CONTENT";
export const SELECT_CONTINENT = "SELECT_CONTINENT";
export const SELECT_DEPARTURE = "SELECT_DEPARTURE";
export const UPDATE_DATE = "UPDATE_DATE";
